name: Sample GitHub Actions
on: [push]
jobs: 
  check-node-version: 
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v3
      - run: chmod 777 ./.github/scripts/script.sh
      - run: ./.github/scripts/script.sh
      - run: echo "CONTENTS OF GIT_HUB_AUTOMATION"
      - run: ls
      - run: pwd
      - uses: actions/upload-artifact@v3
        with: 
          name: web-bundle
          path: ./web-build
